---
title: "Final Project"
author: "Molly Erickson and Tiffany Winter"
date: "11/15/2021"
output: pdf_document
---

```{r setup, include= FALSE}
knitr::opts_chunk$set(echo = FALSE, warning =  FALSE)
```

```{r, fig.cap= "SiO2 concentration at North Beach and Jackson Estuarine Laboratory" }

Silica <- read.csv("~/Thesis_Data/SiO2.csv")
library(ggplot2)
Silica$Date= as.Date(Silica$Date, format = "%m/%d/%Y")
ggplot(data = Silica, aes(x=Date,y=Silica, color=Site)) + geom_line() + 
  labs(x= "Date", y= "Silica (mg SiO2/L)") 

```

```{r, fig.cap= "Tide Height at North Beach and Jackson Estuarine Laboratory" }

Tide <- read.csv("~/Thesis_Data/tide.csv")
library(ggplot2)
Tide$Date= as.Date(Tide$Date, format = "%m/%d/%Y")
ggplot(data = Tide, aes(x=Date,y=TideHeight, color=Site)) + geom_line() + 
  labs(x= "Date", y= "Tide Height (ft)") 
```

```{r, fig.cap= "Salinity at North Beach and Jackson Estuarine Laboratory" }

Salinity <- read.csv("~/Thesis_Data/sali.csv")
library(ggplot2)
Salinity$Date= as.Date(Salinity$Date, format = "%m/%d/%Y")
ggplot(data = Salinity, aes(x=Date,y=Salinity, color=Site)) + geom_line() + 
  labs(x= "Date", y= "Salinity (ppt)") 
```

```{r, fig.cap= "Temperature at North Beach and Jackson Estuarine Laboratory" }

Temp <- read.csv("~/Thesis_Data/temp.csv")
library(ggplot2)
Temp$Date= as.Date(Temp$Date, format = "%m/%d/%Y")
ggplot(data = Temp, aes(x=Date,y=Temp, color=Site)) + geom_line() + 
  labs(x= "Date", y= "Temperature (°C)") 
```

```{r, fig.cap= "Chlorophyll a Concentration at North Beach and Jackson Estuarine Laboratory" }

Chl <- read.csv("~/Thesis_Data/chlorophyllaconc.csv")
library(ggplot2)
Chl$Date= as.Date(Chl$Date, format = "%m/%d/%Y")
ggplot(data = Chl, aes(x=Date,y=Chloro, color=Site)) + geom_line() + 
  labs(x= "Date", y= "Chlorophyll Concentration (ug Chl a/L)") 
```